version: '3'

services:
  mongo:
    image: mongo
    container_name: curator-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data/db:/data/db
      - ./dump:/dump
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curator-api
    restart: always
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:5544:5544"
